pyPOS/blueprints/monitor.py
from flask import Blueprint, render_template, redirect, url_for
from pyPOS.utils.decorators import credentials_level_required, user_domain_required, entry_status_required
from pyPOS.utils.entry import get_entry_by_status, modify_entry_status

bp = Blueprint( 'monitor', __name__, url_prefix='/monitor' )

@bp.route( '/' )
@credentials_level_required( [ 'admin', 'monitor' ] )
def index( ):
    print( dict( get_entry_by_status()['Created'][0] ) )
    return render_template( 'monitor/index.html', entry_dict=get_entry_by_status() )

# Created status

@bp.route( '/cancel/<int:id>/<int:product_id>' )
@credentials_level_required( [ 'admin', 'monitor' ] )
@user_domain_required( [ 'Open' ], [ 'admin', 'monitor' ] )
@entry_status_required( [ 'Created' ] )
def cancel( id, product_id ):
    modify_entry_status( product_id, 'Canceled' )
    return redirect( url_for( 'monitor.index' ) )

@bp.route( '/accept/<int:id>/<int:product_id>' )
@credentials_level_required( [ 'admin', 'monitor' ] )
@user_domain_required( [ 'Open' ], [ 'admin', 'monitor' ] )
@entry_status_required( [ 'Created' ] )
def accept( id, product_id ):
    modify_entry_status( product_id, 'In progress' )
    return redirect( url_for( 'monitor.index' ) )

# In progress status

@bp.route( '/ready/<int:id>/<int:product_id>' )
@credentials_level_required( [ 'admin', 'monitor' ] )
@user_domain_required( [ 'Open' ], [ 'admin', 'monitor' ] )
@entry_status_required( [ 'In progress' ] )
def ready( id, product_id ):
    modify_entry_status( product_id, 'Ready' )
    return redirect( url_for( 'monitor.index' ) )

# Delivered status

@bp.route( '/pay/<int:id>/<int:product_id>' )
@credentials_level_required( [ 'admin', 'monitor' ] )
@user_domain_required( [ 'Open' ], [ 'admin', 'monitor' ] )
@entry_status_required( [ 'Delivered' ] )
def pay( id, product_id ):
    modify_entry_status( product_id, 'Payed' )
    return redirect( url_for( 'monitor.index' ) )

# Canceled status

@bp.route( '/open/<int:id>/<int:product_id>' )
@credentials_level_required( [ 'admin', 'monitor' ] )
@user_domain_required( [ 'Open' ], [ 'admin', 'monitor' ] )
@entry_status_required( [ 'Canceled' ] )
def open( id, product_id ):
    modify_entry_status( product_id, 'Created' )
    return redirect( url_for( 'monitor.index' ) )

pyPOS/templates/monitor/index.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/card_monitor_styles.css' ) }}"/>
{% endblock %}

{% block content %}
    <div class="product-header">
        <h2>Monitor view</h2>
    </div>
    
    {% for status, product_list in entry_dict.items() %}
    
    <div class="product-header">
        <h2 class="depth-3" style="border-width: 0;">{{status}}</h2>
    </div>

    <div class="card-container">
        {% for product in product_list%}



        <div class="card">
            <img src="{{ url_for( 'static', filename='products/' + product.thumbnail|e ) }}">
            <div class="card-content">
                
                <div class="card-info">
                    <p class="title">{{ product.product|e }}</p>
                    <div class="status" >
                        <svg
                            version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            x="0px"
                            y="0px"
                            viewBox="0 0 24.394 24.394"
                            style="enable-background:new 0 0 24.394 24.394;fill:{{ product.color|e }}"
                            xml:space="preserve">
                            <g>
                                <circle cx="12.197" cy="12.197" r="12.197"/>
                            </g>
                        </svg>
    
                        <p>{{ product.status|e }}</p>
                    </div>
                    <p>{{ product.order_name|e }} - {{ product.user|e }}</p>
                    <p>{{ product.entry_timestamp|e }}</p>
                    <p>{{ product.comment|e }}</p>
                    
                </div>

                <div class="card-buttons">
                    {% if product.status == 'Created' %}
                    <a href="{{ url_for( 'monitor.cancel', id=product.order_id, product_id=product.id ) }}" class="card-link">
                        <div class="card-button">Cancel</div>
                    </a>
                    <a href="{{ url_for( 'monitor.accept', id=product.order_id, product_id=product.id ) }}" class="card-link">
                        <div class="card-button">Accept</div>
                    </a>
                    {% elif product.status == 'In progress' %}
                    <a href="{{ url_for( 'monitor.ready', id=product.order_id, product_id=product.id ) }}" class="card-link">
                        <div class="card-button">Ready</div>
                    </a>
                    {% elif product.status == 'Delivered' %}
                    <a href="{{ url_for( 'monitor.pay', id=product.order_id, product_id=product.id ) }}" class="card-link">
                        <div class="card-button">Pay</div>
                    </a>
                    {% elif product.status == 'Canceled' %}
                    <a href="{{ url_for( 'monitor.open', id=product.order_id, product_id=product.id ) }}" class="card-link">
                        <div class="card-button">Open</div>
                    </a>
                    {% endif %}
                </div>

            </div>

        </div>

        {% endfor %}
    </div>
    
    {% endfor %}
{% endblock %}