pyPOS/blueprints/entry.py
from flask import Blueprint, render_template, redirect, url_for, request
from pyPOS.utils.admin import get_products
from pyPOS.utils.order import get_order
from pyPOS.utils.entry import create_entry, modify_entry_status
from pyPOS.utils.decorators import user_domain_required, entry_status_required, credentials_level_required

bp = Blueprint( 'entry', __name__, url_prefix='/entry' )

@bp.route( '/<int:id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
def index( id ):
    return render_template( 'entry/index.html', id=id, order=get_order( id ), products=get_products() )

@bp.route( '/<int:id>/add/<int:product_id>', methods=[ 'GET', 'POST' ] )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
def add( id, product_id ):
    if request.method == 'POST':
        comment = request.form[ 'comment' ]
        create_entry( id, product_id, comment )
        return redirect( url_for( 'order.modify', id=id ) )    
    return render_template( 'entry/add.html', product={'name':'food'} )

@bp.route( '/<int:id>/open/<int:product_id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
@entry_status_required( [ 'Canceled' ] )
def open( id, product_id ):
    modify_entry_status( product_id, 'Created' )
    return redirect( url_for( 'order.modify', id=id ) )

@bp.route( '/<int:id>/deliver/<int:product_id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
@entry_status_required( [ 'Ready' ] )
def deliver( id, product_id ):
    modify_entry_status( product_id, 'Delivered' )
    return redirect( url_for( 'order.modify', id=id ) )

@bp.route( '/<int:id>/cancel/<int:product_id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
@entry_status_required( [ 'Created' ] )
def cancel( id, product_id ):
    modify_entry_status( product_id, 'Canceled' )
    return redirect( url_for( 'order.modify', id=id ) )

pyPOS/templates/entry/add.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/form_styles.css' ) }}"/>
{% endblock %}

{% block content %}
    <div class="product-header">
        <h2>Add {{ product.name|e }}</h2>
    </div>
    <div class="form-container">
    <form method="post" enctype="multipart/form-data">
        <label for="comment">Comment</label>
        <textarea rows="10" cols="60" name="comment"></textarea>

        <input type="submit" value="Add">
    </form>
    </div>
{% endblock %}

pyPOS/templates/entry/index.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/card_styles.css' ) }}"/>
{% endblock %}

{% block content %}
    <div class="product-header">
        <h2>{{ order.name|e }}</h2>
    </div>

    {% for item in products %}
        <div class="product-header">
            <h2 class="depth-{{ item.depth|e }}">{{ item.category|e }}</h2>
        </div>
        
        <div class="card-container">
            {% for product in item.data%}
            <div class="card">
                <img src="{{ url_for( 'static', filename='products/' + product.thumbnail|e ) }}">
                <div class="card-content">
                    <div class="card-info">
                        <p class="title">{{ product.name|e }}</>
                        <p>{{ product.description|e }}</p>
                        <p class="price">${{ product.price|e }}</p>
                    </div>
                    <div class="card-buttons">
                        <a href="{{ url_for( 'entry.add', id=id, product_id=product.id|e ) }}" class="card-link">
                            <div class="card-button">Add</div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% endfor %}

{% endblock %}