pyPOS/blueprints/entry.py
from flask import Blueprint, render_template, redirect, url_for, request
from pyPOS.utils.admin import get_products
from pyPOS.utils.order import get_order
from pyPOS.utils.entry import create_entry, modify_entry_status
from pyPOS.utils.decorators import user_domain_required, entry_status_required, credentials_level_required

bp = Blueprint( 'entry', __name__, url_prefix='/entry' )

@bp.route( '/<int:id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
def index( id ):
    return render_template( 'entry/index.html', id=id, order=get_order( id ), products=get_products() )

@bp.route( '/<int:id>/add/<int:product_id>', methods=[ 'GET', 'POST' ] )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
def add( id, product_id ):
    if request.method == 'POST':
        comment = request.form[ 'comment' ]
        create_entry( id, product_id, comment )
        return redirect( url_for( 'order.modify', id=id ) )    
    return render_template( 'entry/add.html', product={'name':'food'} )

@bp.route( '/<int:id>/open/<int:product_id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
@entry_status_required( [ 'Canceled' ] )
def open( id, product_id ):
    modify_entry_status( product_id, 'Created' )
    return redirect( url_for( 'order.modify', id=id ) )

@bp.route( '/<int:id>/deliver/<int:product_id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
@entry_status_required( [ 'Ready' ] )
def deliver( id, product_id ):
    modify_entry_status( product_id, 'Delivered' )
    return redirect( url_for( 'order.modify', id=id ) )

@bp.route( '/<int:id>/cancel/<int:product_id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( [ 'Open' ] )
@entry_status_required( [ 'Created' ] )
def cancel( id, product_id ):
    modify_entry_status( product_id, 'Canceled' )
    return redirect( url_for( 'order.modify', id=id ) )

pyPOS/blueprints/orders.py
from flask                  import Blueprint, render_template, g, request, redirect, url_for
from pyPOS.utils.order      import get_order_by_status, create_order, modify_order_status
from pyPOS.utils.entry      import get_entry_by_status, modify_entry_status
from pyPOS.utils.decorators import user_domain_required, credentials_level_required

bp = Blueprint( 'order', __name__, url_prefix='/order' )

@bp.route( '/' )
@credentials_level_required( [ 'admin', 'user' ] )
def index():
    id = None
    if g.user[ 'position' ] == 'user': id = g.user[ 'id' ]
    return render_template( 'order/index.html', order_dict=get_order_by_status( id ) )

@bp.route( '/add', methods=[ 'GET', 'POST' ] )
@credentials_level_required( [ 'admin', 'user' ] )
def add():
    if request.method == 'POST':
        name = request.form[ 'name' ]
        id = g.user[ 'id' ]
        create_order( name, id )
        return redirect( url_for( 'order.index' ) )
    return render_template( 'order/add.html' )

@bp.route( '/cancel/<int:id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( ['Open'] )
def cancel( id ):
    modify_order_status( id, 'Canceled' )
    modify_entry_status( id, 'Canceled', order=True )
    return redirect( url_for( 'order.index' ) )

@bp.route( '/open/<int:id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( ['Canceled'] )
def open( id ):
    modify_order_status( id, 'Open' )
    return redirect( url_for( 'order.index' ) )

@bp.route( '/review/<int:id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( ['Canceled', 'Complete'] )
def review( id ):
    return render_template( 'order/review.html', order_id=id, entry_dict=get_entry_by_status( id ) ) 

@bp.route( '/modify/<int:id>' )
@credentials_level_required( [ 'admin', 'user' ] )
@user_domain_required( ['Open'] )
def modify( id ):
    return render_template( 'order/modify.html', order_id=id, entry_dict=get_entry_by_status( id ) ) 
    

pyPOS/templates/order/add.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/form_styles.css' ) }}"/>
{% endblock %}

{% block content %}
    <div class="product-header">
        <h2>Add Order</h2>
    </div>
    <div class="form-container">
    <form method="post" enctype="multipart/form-data">
        <label for="name">Name</label>
        <input name="name" id="name" required>
        <input type="submit" value="Add">
    </form>
    </div>
{% endblock %}

pyPOS/templates/order/index.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/card_order_styles.css' ) }}"/>
{% endblock %}

{% block content %}
<div class="product-header">
    <h2>Take Order</h2>
    <a href="{{ url_for( 'order.add' ) }}" class="add-product">
        <svg
            width="24px"
            height="24px"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path d="M11 10H9v3H6v2h3v3h2v-3h3v-2h-3z"/>
            <path d="M4 22h12c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2H4c-1.103 0-2 .897-2 2v12c0 1.103.897 2 2 2zM4 8h12l.002 12H4V8z"/>
            <path d="M20 2H8v2h12v12h2V4c0-1.103-.897-2-2-2z"/>
        </svg>
    </a>
</div>

{% for status, order_list in order_dict.items() %}
<div class="card-container">
    {% for order in order_list%}
        <div class="card">
            <svg
                version="1.1"
                id="Layer_1"
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                x="0px"
                y="0px"
                viewBox="0 0 512 512"
                style="enable-background:new 0 0 512 512;"
                xml:space="preserve"
            >
            <polygon style="fill:#ADA7A4;" points="72.818,193.801 72.818,500.622 304.924,500.622 347.591,477.867 390.258,500.622 439.182,500.622 439.182,193.801 "/>
            <rect x="304.924" y="315.164" style="fill:#181818;" width="85.333" height="185.458" />
            <rect x="121.742" y="315.164" style="fill:#FFFFFF;" width="134.258" height="136.533" />
            <rect x="118.329" y="11.378" style="fill:#FFB14D;" width="275.342" height="63.716" />
            <g>
                <polygon style="fill:#EE3840;" points="72.818,120.604 38.684,193.801 111.123,216.557 183.561,193.801 211.734,157.203 194.939,120.604" />
                <polygon style="fill:#EE3840;" points="439.182,120.604 473.316,193.801 400.877,216.557 328.439,193.801 300.266,157.203 317.061,120.604" />
            </g>
            <path style="fill:#C21B23;" d="M38.684,193.801c0,40.008,32.431,72.439,72.439,72.439c40.007,0,72.439-32.431,72.439-72.439L38.684,193.801L38.684,193.801z" />
            <polygon style="fill:#FFE1D6;" points="317.061,120.604 194.939,120.604 183.561,193.801 256,216.557 328.439,193.801 " />
            <path style="fill:#FFB14D;" d="M183.561,193.801c0,40.008,32.432,72.439,72.439,72.439s72.439-32.431,72.439-72.439L183.561,193.801L183.561,193.801z" />
            <path style="fill:#C21B23;" d="M328.439,193.801c0,40.007,32.431,72.439,72.439,72.439s72.438-32.431,72.438-72.439H328.439z" />
            <g>
                <path style="fill:#11113F;" d="M390.258,512c-6.283,0-11.378-5.095-11.378-11.378v-174.08h-62.578v174.08c0,6.283-5.095,11.378-11.378,11.378c-6.283,0-11.378-5.095-11.378-11.378V315.164c0-6.283,5.095-11.378,11.378-11.378h85.333c6.283,0,11.378,5.095,11.378,11.378v185.458C401.636,506.905,396.541,512,390.258,512z" />
                <path style="fill:#11113F;" d="M256,463.076H121.742c-6.283,0-11.378-5.095-11.378-11.378V315.164c0-6.283,5.095-11.378,11.378-11.378H256c6.283,0,11.378,5.095,11.378,11.378v136.533C267.378,457.981,262.283,463.076,256,463.076z M133.12,440.32h111.502V326.542H133.12V440.32z" />
                <path style="fill:#11113F;" d="M393.671,86.471H118.329c-6.283,0-11.378-5.095-11.378-11.378V11.378C106.951,5.095,112.046,0,118.329,0h275.342c6.283,0,11.378,5.095,11.378,11.378v63.716C405.049,81.376,399.954,86.471,393.671,86.471z M129.707,63.716h252.587v-40.96H129.707V63.716z" />
                <path style="fill:#11113F;" d="M439.182,512H72.818c-6.283,0-11.378-5.095-11.378-11.378V263.887c0-6.283,5.095-11.378,11.378-11.378c6.283,0,11.378,5.095,11.378,11.378v225.357h343.609V263.887c0-6.283,5.095-11.378,11.378-11.378c6.283,0,11.378,5.095,11.378,11.378v236.735C450.56,506.905,445.465,512,439.182,512z" />
                <path style="fill:#11113F;" d="M400.877,277.618c-30.868,0-57.894-16.774-72.438-41.686c-14.545,24.912-41.57,41.686-72.439,41.686s-57.894-16.774-72.439-41.686c-14.544,24.912-41.57,41.686-72.438,41.686c-46.217,0-83.817-37.6-83.817-83.817c0-1.661,0.363-3.303,1.066-4.809l34.133-73.197c1.868-4.006,5.889-6.568,10.312-6.568h366.364c4.423,0,8.443,2.562,10.312,6.568l34.133,73.197c0.702,1.505,1.066,3.148,1.066,4.809C484.693,240.018,447.093,277.618,400.877,277.618z M339.817,193.801c0,33.669,27.391,61.061,61.06,61.061c32.86,0,59.74-26.088,61.013-58.64l-29.955-64.24H80.065l-29.955,64.24c1.273,32.552,28.153,58.64,61.013,58.64c33.669,0,61.06-27.392,61.06-61.061c0-6.283,5.095-11.378,11.378-11.378c6.283,0,11.378,5.095,11.378,11.378c0,33.669,27.392,61.061,61.061,61.061s61.061-27.392,61.061-61.061c0-6.283,5.095-11.378,11.378-11.378S339.817,187.518,339.817,193.801z" />
                <path style="fill:#11113F;" d="M439.182,205.179H72.818c-6.283,0-11.378-5.095-11.378-11.378c0-6.283,5.095-11.378,11.378-11.378h366.364c6.283,0,11.378,5.095,11.378,11.378C450.56,200.084,445.465,205.179,439.182,205.179z" />
                <path style="fill:#11113F;" d="M141.084,131.982c-6.283,0-11.378-5.095-11.378-11.378V75.093c0-6.283,5.095-11.378,11.378-11.378c6.283,0,11.378,5.095,11.378,11.378v45.511C152.462,126.887,147.367,131.982,141.084,131.982z" />
                <path style="fill:#11113F;" d="M370.916,131.982c-6.283,0-11.378-5.095-11.378-11.378V75.093c0-6.283,5.095-11.378,11.378-11.378s11.378,5.095,11.378,11.378v45.511C382.293,126.887,377.198,131.982,370.916,131.982z" />
                <path style="fill:#11113F;" d="M188.881,171.047c-0.583,0-1.17-0.044-1.762-0.137c-6.209-0.965-10.46-6.781-9.495-12.99l6.072-39.063c0.965-6.21,6.796-10.461,12.99-9.495c6.209,0.965,10.46,6.781,9.495,12.99l-6.072,39.063C199.236,167.033,194.394,171.047,188.881,171.047z" />
                <path style="fill:#11113F;" d="M323.119,171.047c-5.513,0-10.356-4.014-11.228-9.631l-6.072-39.063c-0.966-6.209,3.286-12.025,9.495-12.99c6.207-0.969,12.025,3.286,12.99,9.495l6.072,39.063c0.966,6.209-3.286,12.025-9.495,12.99C324.289,171.002,323.7,171.047,323.119,171.047z" />
            </g>
            </svg>

            
            <div class="card-content">
                
                <div class="card-info">
                    <p class="title">{{ order.name|e }}</p>
                    <div class="status" >

                        <svg
                            version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            x="0px"
                            y="0px"
                            viewBox="0 0 24.394 24.394"
                            style="enable-background:new 0 0 24.394 24.394;fill:{{ order.color|e }}"
                            xml:space="preserve">
                            <g>
                                <circle cx="12.197" cy="12.197" r="12.197"/>
                            </g>
                        </svg>

                        <p>{{ order.status|e }}</p>
                    </div>
                    <p>{{ order.username|e }}</p>
                    <p>{{ order.timestamp|e }}</p>
                </div>

                <div class="card-buttons">    
                    {% if order.status == 'Open' %}
                    <a href="{{ url_for( 'order.modify', id=order.id|e ) }}" class="card-link">
                        <div class="card-button">Modify</div>
                    </a>
                    <a href="{{ url_for( 'order.cancel', id=order.id|e ) }}" class="card-link">
                        <div class="card-button">Cancel</div>
                    </a>
                    {% else %}
                    <a href="{{ url_for( 'order.review', id=order.id|e ) }}" class="card-link">
                        <div class="card-button">Review</div>
                    </a>
                    {% if order.status == 'Canceled' %}
                    <a href="{{ url_for( 'order.open', id=order.id|e ) }}" class="card-link">
                        <div class="card-button">Open</div>
                    </a>
                    {% endif %}
                    {% endif %}
                </div>
            </div>

        </div>
    {% endfor %}
</div>
<div class="product-header">
    <h2></h2>
</div>
{% endfor %}
{% endblock %}

pyPOS/templates/order/modify.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/card_styles.css' ) }}"/>
{% endblock %}

{% block content %}
    <div class="product-header">
        <h2>Order#</h2>
        <a href="{{ url_for( 'entry.index', id=order_id ) }}" class="add-product">
            <svg
                width="24px"
                height="24px"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path d="M11 10H9v3H6v2h3v3h2v-3h3v-2h-3z"/>
                <path d="M4 22h12c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2H4c-1.103 0-2 .897-2 2v12c0 1.103.897 2 2 2zM4 8h12l.002 12H4V8z"/>
                <path d="M20 2H8v2h12v12h2V4c0-1.103-.897-2-2-2z"/>
            </svg>
        </a>
    </div>
    
    <div class="card-container">
        {% for product in product_list%}
            <div class="card">
                <img src="{{ url_for( 'static', filename='products/' + product.thumbnail|e ) }}">
                <div class="card-content">
                    <div class="card-info">
                        <p class="title">{{ product.product|e }}</>
                        <p>{{ product.comment|e }}</p>
                        <p class="price">${{ product.price|e }}</p>
                        
                    </div>
                    <div class="card-buttons">
                        
                        <div class="status" >

                            <svg
                                version="1.1"
                                xmlns="http://www.w3.org/2000/svg"
                                xmlns:xlink="http://www.w3.org/1999/xlink"
                                x="0px"
                                y="0px"
                                viewBox="0 0 24.394 24.394"
                                style="enable-background:new 0 0 24.394 24.394;fill:{{ product.color|e }}"
                                xml:space="preserve">
                                <g>
                                    <circle cx="12.197" cy="12.197" r="12.197"/>
                                </g>
                            </svg>
    
                            <p>{{ product.status|e }}</p>
                        </div>
                        
                        <a href="#" class="card-link">
                            <div class="card-button">Delete</div>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

pyPOS/templates/order/review.html
{% extends 'base.html' %}

{% block css_imports %}
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/card_styles.css' ) }}"/>
{% endblock %}

{% block content %}
    <div class="product-header">
        <h2>Order#</h2>
        <a href="{{ url_for( 'entry.index', id=order_id ) }}" class="add-product">
            <svg
                width="24px"
                height="24px"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path d="M11 10H9v3H6v2h3v3h2v-3h3v-2h-3z"/>
                <path d="M4 22h12c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2H4c-1.103 0-2 .897-2 2v12c0 1.103.897 2 2 2zM4 8h12l.002 12H4V8z"/>
                <path d="M20 2H8v2h12v12h2V4c0-1.103-.897-2-2-2z"/>
            </svg>
        </a>
    </div>
    


    {% for status, product_list in entry_dict.items() %}
    <div class="card-container">
        {% for product in product_list%}
            <div class="card">
                <img src="{{ url_for( 'static', filename='products/' + product.thumbnail|e ) }}">
                <div class="card-content">
                    <div class="card-info">
                        <p class="title">{{ product.product|e }}</>
                        <p>{{ product.comment|e }}</p>
                        <p class="price">${{ product.price|e }}</p>
                        
                    </div>
                    <div class="card-buttons">
                        
                        <div class="status" >

                            <svg
                                version="1.1"
                                xmlns="http://www.w3.org/2000/svg"
                                xmlns:xlink="http://www.w3.org/1999/xlink"
                                x="0px"
                                y="0px"
                                viewBox="0 0 24.394 24.394"
                                style="enable-background:new 0 0 24.394 24.394;fill:{{ product.color|e }}"
                                xml:space="preserve">
                                <g>
                                    <circle cx="12.197" cy="12.197" r="12.197"/>
                                </g>
                            </svg>
    
                            <p>{{ product.status|e }}</p>
                        </div>
                        
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    
    <div class="product-header">
        <h2></h2>
    </div>
    {% endfor %}
{% endblock %}