pyPOS/blueprints/auth.py
from pyPOS.utils.db import getDB
from pyPOS.utils.auth import authenticate
from pyPOS.utils.decorators import credentials_not_required, credentials_required
from flask import Blueprint, request, render_template, url_for, redirect, session, g, flash

bp = Blueprint( "auth", __name__, url_prefix="/auth" )

@bp.before_app_request
def load_logged_user():
    id = session.get( 'user_id' )
    if id:
        g.user = getDB().execute(
            'SELECT * FROM user WHERE id = ?', ( id, )
        ).fetchone()
    else:
        g.user = None

@bp.route( "/login", methods=("GET", "POST") )
@credentials_not_required
def login():
    error = None
    if request.method == "POST":
        username = request.form.get( 'username', None )
        password = request.form.get( 'password', None )
        error = authenticate( username, password )
        if not error:
            return redirect( url_for( "index.index" ) )
        flash( error )
    elif request.method == 'GET' and len( request.args.keys() ):
        username = request.args.get( 'username', None )
        password = request.args.get( 'password', None )
        error = authenticate( username, password )
        if not error:
            return redirect( url_for( "index.index" ) )
        flash( error )    
    return render_template( "auth/login.html" )

@bp.route( '/logout' )
@credentials_required
def logout():
    session.clear()
    return redirect( url_for( "index.index" ) )

pyPOS/templates/base.html
<!DOCTYPE html>
<title></title>
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/base_styles.css' ) }}"/>
{% block css_imports %}
{% endblock %}
<body>
<nav class="navbar">
    <ul class="navbar-nav">
        <li class="logo">
            <a href="{{ url_for( 'index.index' ) }}" class="nav-link">
                <span class="logo-text">Logo</span>
                <svg
                    version="1.1"
                    id="Capa_1"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    x="0px" y="0px"
                    viewBox="0 0 217.061 217.061"
                    style="enable-background:new 0 0 217.061 217.061;"
                    xml:space="preserve"
                >
                    <path d="M182.198,205.491c-6.62,7.785-17.241,11.569-32.467,11.569c-0.002,0-0.005,0-0.008,0c-6.335-0.001-13.6-0.681-21.592-2.021 c-66.912-11.219-70.308-34.4-70.308-71.295c0-27.397,17.425-37.19,28.179-40.625c-6.74-6.68-16.894-19.259-19.569-36.382 c-3.199-20.477,8.116-32.872,13.94-37.769l-5.496-8.878c-0.938-1.516-0.761-3.469,0.436-4.79l7.752-8.562 c0.87-0.962,2.155-1.441,3.44-1.287c1.288,0.154,2.421,0.923,3.04,2.063l6.927,12.752L99.3,19.63L97.803,6.452 c-0.128-1.132,0.232-2.266,0.991-3.116S100.638,2,101.777,2h11.605c2.187,0,3.968,1.756,4,3.943l0.132,9.239l3.766-0.128 l1.706-11.634c0.311-2.116,2.239-3.613,4.358-3.399l9.938,1c2.168,0.218,3.763,2.132,3.586,4.305l-1.298,15.946l8.303,10.167 c0.696,0.853,1.01,1.955,0.868,3.046c-0.142,1.091-0.728,2.076-1.619,2.723c-0.179,0.13-17.976,13.117-23.929,24.322 c-3.547,6.678-3.332,13.618-1.286,17.021c0.542,0.902,1.181,1.463,1.665,1.463l0.125-0.01c0.736-0.458,1.81-3.803,2.521-6.017 c1.522-4.744,3.418-10.647,7.926-16.11c7.304-8.849,19.067-15.523,27.363-15.523c2.592,0,4.786,0.629,6.521,1.868 c6.455,4.61,7.282,19.607,7.381,24.094c0.042,1.889-1.244,3.55-3.083,3.982l-12.937,3.044c-1.98,0.466-5.396,1.528-6.012,3.4 c-0.384,1.167-0.434,4.876,7.385,14.091c10.742,12.661,20.844,26.847,26.392,60.924 C189.802,170.018,193.427,192.288,182.198,205.491z M69.428,97.372c-0.119-0.208-11.955-20.898-13.186-33.036 c-1.112-10.959,3.209-16.138,3.356-16.312c0.83-0.913,1.192-2.157,0.981-3.373s-0.97-2.266-2.059-2.847 c-0.479-0.256-4.831-2.5-9.803-2.5c-3.324,0-6.288,1.035-8.571,2.992c-5.669,4.859-4.685,23.784-3.35,36.148 c-3.29,3.288-7.141,11.399-9.249,30.762c-3.204,29.435,14.911,49.486,15.684,50.325c0.775,0.841,1.849,1.291,2.943,1.291 c0.014,0,0.028,0,0.042,0c2.198-0.013,3.977-1.799,3.977-4c0-0.271-0.027-0.535-0.078-0.79c-0.229-2.515-1.404-17.81,2.393-31.84 c3.869-14.3,15.376-21.317,15.48-21.379C69.879,101.702,70.522,99.274,69.428,97.372z"/>
                </svg>
            </a>
        </li>
        {% if g.user %}
            {% if g.user.position == 'admin' %}
                <li class="nav-item">
                    <a href="{{ url_for( 'admin-products.index' ) }}" class="nav-link">
                        <svg
                            width="24px"
                            height="24px"
                            viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path d="M19.148 2.971A2.008 2.008 0 0 0 17.434 2H6.566c-.698 0-1.355.372-1.714.971L2.143 7.485A.995.995 0 0 0 2 8a3.97 3.97 0 0 0 1 2.618V19c0 1.103.897 2 2 2h14c1.103 0 2-.897 2-2v-8.382A3.97 3.97 0 0 0 22 8a.995.995 0 0 0-.143-.515l-2.709-4.514zm.836 5.28A2.003 2.003 0 0 1 18 10c-1.103 0-2-.897-2-2 0-.068-.025-.128-.039-.192l.02-.004L15.22 4h2.214l2.55 4.251zM10.819 4h2.361l.813 4.065C13.958 9.137 13.08 10 12 10s-1.958-.863-1.993-1.935L10.819 4zM6.566 4H8.78l-.76 3.804.02.004C8.025 7.872 8 7.932 8 8c0 1.103-.897 2-2 2a2.003 2.003 0 0 1-1.984-1.749L6.566 4zM10 19v-3h4v3h-4zm6 0v-3c0-1.103-.897-2-2-2h-4c-1.103 0-2 .897-2 2v3H5v-7.142c.321.083.652.142 1 .142a3.99 3.99 0 0 0 3-1.357c.733.832 1.807 1.357 3 1.357s2.267-.525 3-1.357A3.99 3.99 0 0 0 18 12c.348 0 .679-.059 1-.142V19h-3z"/>
                        </svg>
                        <span class="link-text">Products</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for( 'admin-users.index' ) }}" class="nav-link">
                        <svg
                            width="24px"
                            height="24px"
                            viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg"
                            xml:space="preserve"
                        >
                            <path d="M3 11h8V3H3v8zm2-6h4v4H5V5zM3 21h8v-8H3v8zm2-6h4v4H5v-4zM13 3v8h8V3h-8zm6 6h-4V5h4v4zM13 13h2v2h-2zM15 15h2v2h-2zM13 17h2v2h-2zM17 17h2v2h-2zM19 19h2v2h-2zM15 19h2v2h-2zM17 13h2v2h-2zM19 15h2v2h-2z"/>
                        </svg>
                        <span class="link-text">Users</span>
                    </a>
                </li>
            
            {% endif %}
            {% if g.user.position in [ 'monitor', 'admin' ] %}
            
                <li class="nav-item">
                    <a href="{{ url_for( 'monitor.index' ) }}" class="nav-link">
                        <svg
                            width="24px"
                            height="24px"
                            viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path d="M19 3h-2.25a1 1 0 0 0-1-1h-7.5a1 1 0 0 0-1 1H5c-1.103 0-2 .897-2 2v15c0 1.103.897 2 2 2h14c1.103 0 2-.897 2-2V5c0-1.103-.897-2-2-2zm0 17H5V5h2v2h10V5h2v15z"/>
                        </svg>
                        <span class="link-text">Monitor</span>
                    </a>
                </li>

            {% endif %}
            {% if g.user.position in [ 'user', 'admin' ] %}

                <li class="nav-item">
                    <a href="{{ url_for( 'order.index' ) }}" class="nav-link">
                        <svg
                            width="24px"
                            height="24px"
                            viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path d="m7 17.013 4.413-.015 9.632-9.54c.378-.378.586-.88.586-1.414s-.208-1.036-.586-1.414l-1.586-1.586c-.756-.756-2.075-.752-2.825-.003L7 12.583v4.43zM18.045 4.458l1.589 1.583-1.597 1.582-1.586-1.585 1.594-1.58zM9 13.417l6.03-5.973 1.586 1.586-6.029 5.971L9 15.006v-1.589z"/>
                            <path d="M5 21h14c1.103 0 2-.897 2-2v-8.668l-2 2V19H8.158c-.026 0-.053.01-.079.01-.033 0-.066-.009-.1-.01H5V5h6.847l2-2H5c-1.103 0-2 .897-2 2v14c0 1.103.897 2 2 2z"/>
                        </svg>
                        <span class="link-text">Take Order</span>
                    </a>
                </li>

            {% endif %}
            <li class="nav-item">
                <a href="{{ url_for( 'auth.logout' ) }}" class="nav-link">
                    <svg
                        width="24px"
                        height="24px"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path d="m2 12 5 4v-3h9v-2H7V8z"/>
                        <path d="M13.001 2.999a8.938 8.938 0 0 0-6.364 2.637L8.051 7.05c1.322-1.322 3.08-2.051 4.95-2.051s3.628.729 4.95 2.051 2.051 3.08 2.051 4.95-.729 3.628-2.051 4.95-3.08 2.051-4.95 2.051-3.628-.729-4.95-2.051l-1.414 1.414c1.699 1.7 3.959 2.637 6.364 2.637s4.665-.937 6.364-2.637c1.7-1.699 2.637-3.959 2.637-6.364s-.937-4.665-2.637-6.364a8.938 8.938 0 0 0-6.364-2.637z"/>
                    </svg>
                    <span class="link-text">Log Out</span>
                </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a href="{{ url_for( 'auth.login' ) }}" class="nav-link">
                    <svg
                        width="24px"
                        height="24px"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path d="m10.998 16 5-4-5-4v3h-9v2h9z"/>
                        <path d="M12.999 2.999a8.938 8.938 0 0 0-6.364 2.637L8.049 7.05c1.322-1.322 3.08-2.051 4.95-2.051s3.628.729 4.95 2.051S20 10.13 20 12s-.729 3.628-2.051 4.95-3.08 2.051-4.95 2.051-3.628-.729-4.95-2.051l-1.414 1.414c1.699 1.7 3.959 2.637 6.364 2.637s4.665-.937 6.364-2.637C21.063 16.665 22 14.405 22 12s-.937-4.665-2.637-6.364a8.938 8.938 0 0 0-6.364-2.637z"/>
                    </svg>
                    <span class="link-text">Log In</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>